# Generated by Django 4.1.5 on 2023-01-15 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('available_income', models.FloatField(verbose_name='monthly income to use for calculations')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256)),
                ('amount', models.FloatField()),
                ('date', models.DateField()),
                ('payed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.person')),
            ],
        ),
    ]
