# Generated by Django 4.1.5 on 2023-01-26 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='payed_by',
            new_name='paid_by',
        ),
    ]
