# Generated by Django 4.1.5 on 2023-02-02 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_rename_payed_by_expense_paid_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='recurs_monthly',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
