# Generated by Django 4.1.5 on 2023-02-12 19:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_expense_recurs_monthly'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaySpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
        migrations.AddField(
            model_name='expense',
            name='pay_space',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='expenses.payspace'),
        ),
        migrations.AddField(
            model_name='person',
            name='pay_spaces',
            field=models.ManyToManyField(to='expenses.payspace'),
        ),
    ]
