# Generated by Django 4.1.5 on 2023-02-12 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expenses', '0004_payspace_expense_pay_space_person_pay_spaces'),
    ]

    operations = [
        migrations.AddField(
            model_name='payspace',
            name='allowed_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='person',
            name='pay_spaces',
        ),
        migrations.AddField(
            model_name='person',
            name='pay_spaces',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='expenses.payspace'),
        ),
    ]
