# Generated by Django 4.1.5 on 2023-02-13 01:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expenses', '0005_payspace_allowed_users_remove_person_pay_spaces_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='pay_spaces',
            new_name='pay_space',
        ),
        migrations.CreateModel(
            name='ExpenseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.payspace')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
