# Generated by Django 4.1.5 on 2023-02-20 21:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expenses', '0007_remove_payspace_allowed_users_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExpenseUser',
            new_name='Device',
        ),
    ]
