# Generated by Django 4.1.5 on 2023-02-20 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expenses', '0008_rename_expenseuser_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='pay_space',
        ),
        migrations.AddField(
            model_name='device',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='expenses.person'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='device', to=settings.AUTH_USER_MODEL),
        ),
    ]
