# Generated by Django 4.1.5 on 2023-02-22 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0009_remove_device_pay_space_device_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='expenses.person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='pay_space',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='expenses.payspace'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('date', models.DateField()),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='was_paid', to='expenses.person')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_paid', to='expenses.person')),
            ],
        ),
        migrations.AddField(
            model_name='expense',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='expenses.payment'),
        ),
    ]
