# Generated by Django 4.1.5 on 2023-02-23 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0010_alter_device_person_alter_person_pay_space_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='settled',
            field=models.BooleanField(default=False),
        ),
    ]
