# Generated by Django 4.1.5 on 2023-02-23 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0011_expense_settled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='settled',
        ),
        migrations.AlterField(
            model_name='expense',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_list', to='expenses.payment'),
        ),
    ]
