# Generated by Django 4.1.5 on 2023-02-23 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0012_remove_expense_settled_alter_expense_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='date',
        ),
        migrations.AddField(
            model_name='payment',
            name='timestamp',
            field=models.DateTimeField(default='2020-01-01'),
            preserve_default=False,
        ),
    ]
