# Generated by Django 4.1.5 on 2023-03-04 19:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0015_multitoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='reference',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
